version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    networks:
      - hitc-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - hitc-network

networks:
  hitc-network:
    driver: bridge
